### ISSUE TITLE
JSON_MERGE error

### ISSUE THREAD

**Issue by cydrickn** [SyslogicNL/DoctrineJsonFunctions#17]
Seem that Json merge is not working

**Notice: Undefined property: Syslogic\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonMerge::$firstJsonPathExpr**

Since this is in line 64 of JsonMerge
The variable is wrong, maybe this is $this->firstJsonDocExpr not $this->firstJsonPathExpr

**Comment by hayrie** [comment]
Yes you are right.
I changed line 64 from
**$this->jsonDocs[] = $this->firstJsonPathExpr;**
to
**$this->jsonDocs[] = $this->firstJsonDocExpr;**
and suddenly it works ;-)

**Comment by Hikariii** [comment]
@hayrie Thanks for the fix!
