### ISSUE TITLE
Support for JSON_EXISTS MariaDB 10.2.3

### ISSUE THREAD

**Issue by aalwash** [SyslogicNL/DoctrineJsonFunctions#24]
At this moment this library is missing some JSON_* functions from MariaDB

Since I'm not an expert in doctrine QDL systems, I will only add JSON_EXISTS for now.
https://mariadb.com/kb/en/library/json_exists/

The syntax is similar to JSON_KEYS(), so I will extend that one and add the function.

**Comment by Hikariii** [comment]
https://github.com/SyslogicNL/DoctrineJsonFunctions/pull/25
