### ISSUE TITLE
Added to packagist

### ISSUE THREAD

**Issue by TNAJanssen** [SyslogicNL/DoctrineJsonFunctions#3]
Hi,

I added it to packagist, so it isn't necessary to add the repository anymore.

Greetings

**Comment by Hikariii** [comment]
Just saw you also claimed the namespace in the progress of adding it... This makes it hard for us to add new packages to the same namespace. Could you transfer maintainership of that namespace?

![image](https://cloud.githubusercontent.com/assets/1484903/14309301/e665601c-fbdb-11e5-9675-30287716fa58.png)

**Comment by Hikariii** [comment]
@TNAJanssen I sent you an e-mail to the address from your github profile.
