### ISSUE TITLE
How to integrate this extension with symfony2

### ISSUE THREAD

**Issue by Mathangaweera** [SyslogicNL/DoctrineJsonFunctions#5]
Hi,

Thank you very much for developing this module. Let me know the steps that I should follow to integrate this extension to symfony2 with config.yml file (symfony config.yml).

Thanks

**Comment by MichaelHindley** [comment]
Add the following to your config.yml under the doctrine config, you need to add each function you want to use in the manner below, one per line.


    orm:
        dql:
            string_functions:
                JSON_EXTRACT: Syslogic\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract

**Comment by Hikariii** [comment]
I'll close this for now. If anything is unclear please comment and reopen.
