### ISSUE TITLE
Operation 'JSON_CONTAINS' is not supported by platform. (MYSQL 5.7)

### ISSUE THREAD

**Issue by laurisnets** [SyslogicNL/DoctrineJsonFunctions#7]
`$platform = $sqlWalker->getConnection()->getDatabasePlatform();`

I am running mysql 5.7
`get_class($platform) `returns "Doctrine\DBAL\Platforms\MySqlPlatform"

But I got this error:
> Operation 'JSON_CONTAINS' is not supported by platform.
> 500 Internal Server Error - DBALException

If I remove `if ($platform instanceof MySQL57Platform) {` from JsonContains it works nice

**Comment by Hikariii** [comment]
This check is based on JSON function being only available from mysl 5.7 and up.
The Doctrine Dbal docs reference has this to say about it: https://github.com/doctrine/dbal/blob/61e1f860a304c3fb6961ecbec36927b5f20b71c6/docs/en/reference/platforms.rst#mysql

- Are you sure you're using a version of Docrine DBAL that supports this variable?
- Can you debug and tell me what the version is you encountered?

**Comment by Hikariii** [comment]
It could be you're using Doctrine and Dbal version 2.4.
There this variable is not yet included.

**Comment by laurisnets** [comment]
I am using "doctrine/dbal": "<2.5"

**Comment by Hikariii** [comment]
I'm considering removing this check because of your issue with it.
If one has the wrong platform, these functions won't work anyway.

**Comment by laurisnets** [comment]
If I changed doctrine/dbal to 2.5 then it works.
But I am not sure if its time to change dbal version in my project.
It would be very nice if you removed this check.

**Comment by Hikariii** [comment]
Could you recheck if it works, check is moved to a general mysql check

**Comment by laurisnets** [comment]
Changes should be made also in composer package?
https://packagist.org/packages/syslogic/doctrine-json-functions

**Comment by Hikariii** [comment]
just updated it

**Comment by laurisnets** [comment]
Thanks, it works now.

Have a good day!
